server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/asset_db
spring.datasource.username=root
spring.datasource.password=root
info.app.name=Asset Service
info.app.description=Manages renewable energy assets
info.app.version=1.0.0
resilience4j.circuitbreaker.instances.assetService.sliding-window-size=5
resilience4j.circuitbreaker.instances.assetService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.assetService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.assetService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.assetService.register-health-indicator=true
resilience4j.circuitbreaker.instances.assetService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.retry.instances.assetService.max-attempts=3
resilience4j.retry.instances.assetService.wait-duration=2s
resilience4j.retry.instances.assetService.retry-exceptions=java.io.IOException,feign.FeignException