server.port=8086
spring.datasource.url=jdbc:mysql://localhost:3306/billing_db
spring.datasource.username=root
spring.datasource.password=root
info.app.name=Billing Service
info.app.description=Manages billing invoices and payments
info.app.version=1.0.0

