server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/demand_response_db
spring.datasource.username=root
spring.datasource.password=root
info.app.name=Demand Response Service
info.app.description=Manages DR programs and events
info.app.version=1.0.0
