server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/identity_db
spring.datasource.username=root
spring.datasource.password=root
info.app.name=Identity Service
info.app.description=Handles authentication and user management
info.app.version=1.0.0
resilience4j.circuitbreaker.instances.identityService.sliding-window-size=5
resilience4j.circuitbreaker.instances.identityService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.identityService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.identityService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.identityService.register-health-indicator=true
resilience4j.circuitbreaker.instances.identityService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.retry.instances.identityService.max-attempts=3
resilience4j.retry.instances.identityService.wait-duration=2s
resilience4j.retry.instances.identityService.retry-exceptions=java.io.IOException,feign.FeignException